### ISSUE TITLE
failed to load module: zsh/pcre

### ISSUE THREAD

**Issue by jdavis** [tarruda/zsh-fuzzy-match#6]
I am running OS X 10.8 and got this error when trying to use it:

``` bash
_fuzzy-match-file-glob:1: failed to load module `zsh/pcre': dlopen(/usr/lib/zsh/4.3.11/zsh/pcre.so, 9): image not found
```

I'm using the zsh that comes with OS X: `zsh 4.3.11 (i386-apple-darwin12.0)`

**Comment by shemerey** [comment]
i have same issue

**Comment by tarruda** [comment]
I dont use OS X, but I guess it doesn't bundle the pcre module needed for this plugin. You guys should uninstall OSX's version of zsh and install zsh from source

**Comment by jdavis** [comment]
I installed zsh through Homebrew using these [instructions](http://zanshin.net/2013/09/03/how-to-use-homebrew-zsh-instead-of-max-os-x-default/) and it worked fine. Check that out @shemerey.

**Comment by shemerey** [comment]
it works for me,  but from time to time it gets 99% cpu and becomes  huge memory consumer. I can't find problem, could be my fault or miss-configuration
