### ISSUE TITLE
Shelr Demo dead link

### ISSUE THREAD

**Issue by mjperrone** [tarruda/zsh-fuzzy-match#9]
The link at the bottom of the readme is dead. I was hoping to get an inline gif of the behavior like all the fancy plugins are doing these days.

If I install anyways and like it, I'll add it myself, but without the gif will I install it? Not sold yet.

**Comment by tarruda** [comment]
This plugin is very alpha and incomplete, I don't recommend using it. There better alternatives available:
- https://github.com/garybernhardt/selecta
- https://github.com/junegunn/fzf
